service: multiverse-reader-server

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    LIBRARY_PATH: /Users/tim/workspace/multiverse-reader/library
    CACHE_PATH: /Users/tim/workspace/multiverse-reader/.cache
    FILE_SERVER_PATH: http://localhost:5000

functions:
  graphql:
    handler: src/handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: src/handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
